name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm packages
        run: yes yes | npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          [[ -n ${SQUARESPACE_DEPLOYMENT_USER} ]] \
            && [[ -n ${SQUARESPACE_DEPLOYMENT_PASSWORD} ]] \
            && [[ -n ${SQUARESPACE_DEPLOYMENT_EMAIL} ]] \
            && [[ -n ${SQUARESPACE_DEPLOYMENT_NAME} ]] \
            || exit
          tee ~/.netrc > /dev/null << EOF
            machine jeanpierre-hohmann.squarespace.com
            login ${SQUARESPACE_DEPLOYMENT_USER}
            password ${SQUARESPACE_DEPLOYMENT_PASSWORD}
          EOF
          git config --global user.email "${SQUARESPACE_DEPLOYMENT_EMAIL}"
          git config --global user.name "${SQUARESPACE_DEPLOYMENT_NAME}"
          npm run deploy
        env:
          SQUARESPACE_DEPLOYMENT_USER: ${{ secrets.SQUARESPACE_DEPLOYMENT_USER }}
          SQUARESPACE_DEPLOYMENT_PASSWORD: ${{ secrets.SQUARESPACE_DEPLOYMENT_PASSWORD }}
          SQUARESPACE_DEPLOYMENT_EMAIL: ${{ secrets.SQUARESPACE_DEPLOYMENT_EMAIL }}
          SQUARESPACE_DEPLOYMENT_NAME: ${{ secrets.SQUARESPACE_DEPLOYMENT_NAME }}
